version: '3'
services:
  dashboard:
    build: ./dashboard
    ports:
      - "8050:8050"
  airflow:
    build: ./airflow
    ports:
     - "8081:8081"
    volumes:
     - /home/aitor/Escritorio/docker/tfm_BI_BIGDATA/airflow/dags:/root/airflow/dags
  db:
    image: "mariadb/columnstore"
    restart: always
    environment:
         MARIADB_ROOT_PASSWORD: admin
         MARIADB_DATABASE: test
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  spark:
    network_mode: host
    depends_on:
      - airflow
    build: ./spark
    ports:
      - "8998:8998"
