version: '3'
services:
  spark:
    networks:
      - spark
      - database
    build: ./spark
    ports:
      - "8998:8998"
    volumes:
      - ./data:/data
  drill:
    build: ./drill
    volumes:
      - ./data:/data
    networks:
      - database
    ports:
      - "8047:8047"
    stdin_open: true
    tty: true
  airflow:
    build: ./airflow
    ports:
     - "8081:8081"
    networks:
     - spark
    volumes:
     - ./airflow/dags:/root/airflow/dags
     - ./data:/data
  dashboard:
    build: ./dashboard
    volumes:
      - ./dashboard/server:/dashboard/server
    networks:
     - database
    ports:
     - "8050:8050"
    stdin_open: true
    tty: true

networks:
    spark:
    database:
