version: '3'
services:
  dashboard:
    build: ./dashboard
    volumes:
      - /home/aitor/Escritorio/docker/tfm_BI_BIGDATA/dashboard/server:/dashboard/server
    networks:
     - database
    ports:
     - "8050:8050"
  airflow:
    build: ./airflow
    ports:
     - "8081:8081"
    networks:
     - spark
    volumes:
     - /home/aitor/Escritorio/docker/tfm_BI_BIGDATA/airflow/dags:/root/airflow/dags
  db:
    image: "mariadb/columnstore"
    restart: always
    environment:
         MARIADB_ROOT_PASSWORD: admin
         MARIADB_DATABASE: test
    networks:
      - database
  adminer:
    image: adminer
    restart: always
    networks:
      - database     
    ports:
      - "8080:8080"
  spark:
    networks:
      - spark
      - database
    build: ./spark
    ports:
      - "8998:8998"
    volumes:
      - /home/aitor/Escritorio/docker/tfm_BI_BIGDATA/data:/data
  drill:
    build: ./drill
    volumes:
      - /home/aitor/Escritorio/docker/tfm_BI_BIGDATA/data:/data
    networks:
      - database
    ports:
      - "8047:8047"
    stdin_open: true
    tty: true
           
networks:
    spark:
    database:
