TITLE = 'European cities statistics'
TOPIC_SELECTOR_TITLE = "Topic"
VARIABLES_SELECTOR_TITLE = "Statistic"
COUNTRIES_SELECTOR_TITLE = "Country"
CITIES_SELECTOR_TITLE = "City"
YEAR_SELECTOR_TITLE = "Year"
